project:
  type: website
  preview:
    port: 4200

google-analytics: G-4RNWXLMEJR

execute:
  freeze: auto

website:
  title: "Personal Science Tips"
  site-url: https://tips.personalscience.com
  favicon: assets/favicon.ico
  navbar:
    logo: assets/psi-LogoOnly.png
    logo-href: https://personalscience.com
    left:
      - href: microbiome/microbiome.qmd
        text: Microbiome
      - href: https://diycgm.com
        text: CGM

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    link-external-newwindow: true
    



